import { Platform, StyleSheet } from "react-native";

// Mono stand-in for IBM Plex Mono — no font loading, so use the platform mono.
const MONO = Platform.select({ ios: "Menlo", default: "monospace" });

// Level-meter mark, ported from apps/web meter-mark.tsx.
export const METER_BARS = [6, 12, 9, 16, 11, 7];

export const streamScreenStyles = StyleSheet.create({
	actionDisabled: { opacity: 0.35 },
	bottomPanel: { alignItems: "center", gap: 12 },
	brandRow: {
		alignItems: "center",
		flexDirection: "row",
		gap: 10,
		marginBottom: 28,
	},
	buttonDisabled: { opacity: 0.4 },
	buttonPressed: { transform: [{ scale: 0.98 }] },
	container: { backgroundColor: "#07090d", flex: 1 },
	controls: { flex: 1, justifyContent: "space-between", paddingHorizontal: 20 },
	eyebrow: {
		color: "#8a93a2",
		fontFamily: MONO,
		fontSize: 11,
		letterSpacing: 2,
		textTransform: "uppercase",
	},
	formError: {
		borderLeftColor: "#ff8795",
		borderLeftWidth: 2,
		color: "#ff8795",
		fontSize: 14,
		lineHeight: 20,
		marginTop: 16,
		paddingLeft: 12,
		paddingVertical: 6,
	},
	meterBar: { backgroundColor: "#f0f1f2", width: 3 },
	meterMark: { alignItems: "flex-end", flexDirection: "row", gap: 3 },
	wordmark: {
		color: "#f0f1f2",
		fontSize: 20,
		fontWeight: "700",
		letterSpacing: 5,
	},
	format: { color: "rgba(255,255,255,0.72)", fontSize: 12, fontWeight: "700" },
	statBlock: { alignItems: "center", gap: 4 },
	statRow: { flexDirection: "row", gap: 18, justifyContent: "center" },
	stat: { alignItems: "center", gap: 1 },
	statValue: {
		color: "white",
		fontFamily: MONO,
		fontSize: 15,
		fontVariant: ["tabular-nums"],
		fontWeight: "800",
	},
	statCaption: {
		color: "rgba(255,255,255,0.6)",
		fontSize: 10,
		fontWeight: "800",
		letterSpacing: 0.5,
		textTransform: "uppercase",
	},
	bondedLine: { color: "rgba(255,255,255,0.6)", fontSize: 12 },
	input: {
		backgroundColor: "#151922",
		borderColor: "rgba(255,255,255,0.14)",
		borderRadius: 4,
		borderWidth: 1,
		color: "white",
		fontSize: 16,
		marginTop: 28,
		paddingHorizontal: 16,
		paddingVertical: 16,
		width: "100%",
	},
	liveButton: {
		alignItems: "center",
		backgroundColor: "#ff354d",
		borderRadius: 28,
		flexDirection: "row",
		gap: 10,
		justifyContent: "center",
		minWidth: 164,
		paddingHorizontal: 26,
		paddingVertical: 16,
	},
	liveButtonIcon: {
		backgroundColor: "white",
		borderRadius: 7,
		height: 14,
		width: 14,
	},
	liveButtonText: { color: "white", fontSize: 17, fontWeight: "800" },
	liveDot: { backgroundColor: "#ff354d" },
	loading: {
		alignItems: "center",
		backgroundColor: "#07090d",
		flex: 1,
		justifyContent: "center",
	},
	loadingText: { color: "#9aa3b1", marginTop: 12 },
	message: {
		backgroundColor: "rgba(0,0,0,0.62)",
		borderRadius: 10,
		color: "white",
		fontSize: 13,
		overflow: "hidden",
		paddingHorizontal: 12,
		paddingVertical: 8,
		textAlign: "center",
	},
	mainActions: { flexDirection: "row", gap: 12 },
	roundButton: {
		alignItems: "center",
		backgroundColor: "rgba(16,19,25,0.88)",
		borderRadius: 28,
		height: 56,
		justifyContent: "center",
		width: 56,
	},
	roundButtonIcon: { color: "white", fontSize: 22, lineHeight: 24 },
	zoomButton: {
		borderCurve: "continuous",
		borderRadius: 24,
		height: 48,
		overflow: "hidden",
		width: 48,
	},
	zoomButtonFallback: {
		backgroundColor: "rgba(16,19,25,0.68)",
		borderColor: "rgba(255,255,255,0.3)",
		borderWidth: StyleSheet.hairlineWidth,
	},
	zoomButtonPressable: {
		alignItems: "center",
		flex: 1,
		justifyContent: "center",
	},
	zoomButtonSelected: {
		backgroundColor: "rgba(255,53,77,0.72)",
		borderColor: "rgba(255,255,255,0.72)",
	},
	zoomButtonText: {
		color: "white",
		fontSize: 13,
		fontVariant: ["tabular-nums"],
		fontWeight: "800",
	},
	zoomControls: { flexDirection: "row", gap: 10, justifyContent: "center" },
	primaryButton: {
		alignItems: "center",
		backgroundColor: "#f0f1f2",
		borderRadius: 4,
		marginTop: 18,
		padding: 16,
		width: "100%",
	},
	primaryButtonText: { color: "#0b0d11", fontSize: 16, fontWeight: "700" },
	secondaryButton: {
		alignItems: "center",
		borderColor: "rgba(255,255,255,0.14)",
		borderRadius: 4,
		borderWidth: 1,
		marginTop: 10,
		padding: 16,
		width: "100%",
	},
	secondaryButtonText: { color: "white", fontSize: 16, fontWeight: "700" },
	scrim: {
		backgroundColor: "rgba(0,0,0,0.08)",
		bottom: 0,
		left: 0,
		position: "absolute",
		right: 0,
		top: 0,
	},
	settingsLink: {
		backgroundColor: "rgba(255,255,255,0.16)",
		borderRadius: 12,
		paddingHorizontal: 14,
		paddingVertical: 9,
	},
	settingsLinkText: { color: "white", fontSize: 14, fontWeight: "700" },
	topBarButtons: { flexDirection: "row", gap: 8 },
	settingsButton: {
		backgroundColor: "rgba(0,0,0,0.6)",
		borderRadius: 18,
		paddingHorizontal: 14,
		paddingVertical: 8,
	},
	settingsButtonText: { color: "white", fontSize: 12, fontWeight: "800" },
	setup: {
		alignItems: "stretch",
		flex: 1,
		justifyContent: "center",
		padding: 28,
	},
	setupBackground: { backgroundColor: "#07090d", flex: 1 },
	featureBadge: {
		color: "rgba(255,255,255,0.85)",
		fontSize: 10,
		fontWeight: "800",
		letterSpacing: 0.5,
	},
	indicatorPill: {
		alignItems: "center",
		backgroundColor: "rgba(0,0,0,0.6)",
		borderRadius: 18,
		flexDirection: "row",
		gap: 8,
		paddingHorizontal: 12,
		paddingVertical: 8,
	},
	micBar: { borderRadius: 1.5, width: 3 },
	micMeter: {
		alignItems: "flex-end",
		flexDirection: "row",
		gap: 2,
		height: 12,
	},
	statusCluster: {
		alignItems: "center",
		flexDirection: "row",
		flexShrink: 1,
		gap: 8,
	},
	statusDot: {
		backgroundColor: "#8a93a2",
		borderRadius: 4,
		height: 8,
		width: 8,
	},
	statusPill: {
		alignItems: "center",
		backgroundColor: "rgba(0,0,0,0.6)",
		borderRadius: 18,
		flexDirection: "row",
		gap: 8,
		paddingHorizontal: 12,
		paddingVertical: 8,
	},
	statusText: {
		color: "white",
		fontSize: 12,
		fontWeight: "800",
		textTransform: "uppercase",
	},
	stopButton: {
		backgroundColor: "rgba(16,19,25,0.88)",
		borderColor: "white",
		borderWidth: 2,
	},
	stopButtonIcon: { borderRadius: 2 },
	subtitle: {
		color: "#9aa3b1",
		fontSize: 16,
		lineHeight: 23,
		maxWidth: 360,
	},
	textButton: { alignItems: "flex-start", marginTop: 16, paddingVertical: 10 },
	textButtonLabel: { color: "#c4cad4", fontSize: 15, fontWeight: "600" },
	title: {
		color: "white",
		fontSize: 34,
		fontWeight: "700",
		letterSpacing: -0.5,
		marginBottom: 12,
		marginTop: 8,
		textTransform: "uppercase",
	},
	toast: {
		alignItems: "center",
		bottom: 150,
		left: 20,
		position: "absolute",
		right: 20,
	},
	toastContent: {
		alignItems: "center",
		backgroundColor: "rgba(21,25,34,0.96)",
		borderRadius: 12,
		flexDirection: "row",
		gap: 10,
		paddingHorizontal: 16,
		paddingVertical: 12,
	},
	toastText: {
		color: "white",
		flexShrink: 1,
		fontSize: 14,
		fontWeight: "700",
		textAlign: "center",
	},
	topBar: {
		flexDirection: "row",
		gap: 10,
		justifyContent: "space-between",
		paddingTop: 8,
	},
	urlAction: {
		color: "rgba(255,255,255,0.82)",
		fontSize: 13,
		fontWeight: "700",
	},
	urlActions: { flexDirection: "row", gap: 28, marginBottom: 8, marginTop: 2 },
});
